server:
  port: 8701 # 服务提供方
# 指定当前eureka客户端的注册地址，
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8699/eureka
  instance:
    hostname: localhost

ribbon:
  eager-load:
    # 开启ribbon饥饿加载
    enabled: true
    # 配置user-center使用ribbon饥饿加载，多个使用逗号分隔
    clients: user-center
#当前服务名称
spring:
  application:
    name: eureka-service